Лабораторная работа №3 выполнена
FyodorChekan/web-programming pull request #6
Opened 2024-10-07 12:29 UTC by FyodorChekan

2024-10-28 07:45 UTC, FlashAnton requested changes
Здравствуйте!

Не нахожу в репозитории отчёта по лабораторной работе №3.

2024-10-28 11:06 UTC, FyodorChekan commented
> Здравствуйте!
> 
> Не нахожу в репозитории отчёта по лабораторной работе №3.

Здравствуйте! Отчёт приложили.

2024-10-28 20:33 UTC, FlashAnton requested changes
Здравствуйте!

У меня, практически, нет вопросов к работе кроме этого фрагмента:
![image](https://github.com/user-attachments/assets/43b848fb-f6d0-4ca5-94af-5b568fa89501)

Как может "коллизия" двух устойчивых состояний приводить к выходу из программы? Просто не понимаю.

Не понимаю так же почему завершает по Ctrl + Click работу приложение, хотя реально оно продолжает работу после этого?

![image](https://github.com/user-attachments/assets/214b46b5-4822-401e-b98e-c83cf368429f)

Не увидел из сети Петри работу с браузерными диалоговыми окнами, открывающимися в модальном режиме.

2024-11-06 09:12 UTC, FyodorChekan commented
> Здравствуйте!
> 
> У меня, практически, нет вопросов к работе кроме этого фрагмента: ![image](https://private-user-images.githubusercontent.com/95698986/380882532-43b848fb-f6d0-4ca5-94af-5b568fa89501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQ1NjksIm5iZiI6MTczMDg4NDI2OSwicGF0aCI6Ii85NTY5ODk4Ni8zODA4ODI1MzItNDNiODQ4ZmItZjZkMC00Y2E1LTk0YWYtNWI1NjhmYTg5NTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTg2MGU4Zjg1YmI5Mzc1ZTNlNDEwNjRmOWUyOWJjNWEwNjc0MDcwZWM1OThlODU4MTkwZjQwY2E2NWQ0ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nYARhOYNjh8MBxDIRak6ZRW-2MOPA0RxmBnDLsr3xzM)
> 
> Как может "коллизия" двух устойчивых состояний приводить к выходу из программы? Просто не понимаю.
> 
> Не понимаю так же почему завершает по Ctrl + Click работу приложение, хотя реально оно продолжает работу после этого?
> 
> ![image](https://private-user-images.githubusercontent.com/95698986/380883238-214b46b5-4822-401e-b98e-c83cf368429f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODQ1NjksIm5iZiI6MTczMDg4NDI2OSwicGF0aCI6Ii85NTY5ODk4Ni8zODA4ODMyMzgtMjE0YjQ2YjUtNDgyMi00MDFlLWI5OGUtYzgzY2YzNjg0MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTQ3NGNmNmFmYjViOWE4MTJhYjZlNGY2N2EwMDllNTAxNDFhMDljM2VhNDZmOWRlN2NlMmU5MTExYzg4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uKowOnshU3p9XeuYsPLUQQHvuzT-jcf-U2cYEvTvMr0)
> 
> Не увидел из сети Петри работу с браузерными диалоговыми окнами, открывающимися в модальном режиме.

Добрый день! Отчёт исправили.

2024-11-11 13:02 UTC, merged